### ISSUE TITLE
Fails to work for the 0x v2 `Exchange` contract

### ISSUE THREAD

**Issue by reverendus** [trailofbits/rattle#21]
```
➜  rattle git:(master) ✗ python3 rattle-cli.py --input ../code.bytecode -O
Traceback (most recent call last):
  File "rattle-cli.py", line 203, in <module>
    main()
  File "rattle-cli.py", line 48, in main
    ssa = rattle.Recover(args.input.read(), edges=edges, optimize=args.optimize)
  File "/Users/___/Projects/Ethereum/rattle/rattle/recover.py", line 712, in __init__
    self.internal = InternalRecover(filedata, edges, optimize)
  File "/Users/___/Projects/Ethereum/rattle/rattle/recover.py", line 41, in __init__
    self.recover(dispatch)
  File "/Users/___/Projects/Ethereum/rattle/rattle/recover.py", line 75, in recover
    self.identify_blocks(function)
  File "/Users/___/Projects/Ethereum/rattle/rattle/recover.py", line 185, in identify_blocks
    block.set_fallthrough_target(terminator.offset + terminator.insn.size)
  File "/Users/___/Projects/Ethereum/rattle/rattle/ssa.py", line 478, in set_fallthrough_target
    target_block : SSABasicBlock = self.function.blockmap[other]
KeyError: 22707
```

`code.bytecode` created with `cat code.bin | xxd -r -ps > code.bytecode` whereas `code.bin` is https://gist.github.com/reverendus/9151b4d7b154b63fd55ae663fa6465a4.  I'm on the recent `master` i.e. `2ec580f6963ee876b90326576bc328cca0d03c79`.

**Comment by ireneGP** [comment]
I wonder if this tool is being supported?

**Comment by dguido** [comment]
@ireneGP This project is supported, but some of these problems are difficult to fix. Today, it works for most people's use cases but every now and then we'll run across a contract where it has issues. We're planning to spend time adding more comprehensive tests and support to it soon.

**Comment by lsankar4033** [comment]
I assume the tool isnt' being maintained actively anymore? Similar to the original issue poster, I have a contract that rattle isn't working for, but if you guys aren't working on it anymore, I can dig in myself.

And if there's still a discussion slack, where is it?

**Comment by dguido** [comment]
Hey @lsankar4033, we're still supporting rattle and will help debug and address any issues you can find. Please file an issue that includes the contract you ran rattle on and the error details. We'll take a look. The Slack is accessible at https://empireslacking.herokuapp.com in the #ethereum channel.

**Comment by lsankar4033** [comment]
cool, will do!

**Comment by CarstenNZ** [comment]
@lsankar4033 
The link to `byte.code` is broken. Please make it available if you are still interested.
